In [1]:
import pandas as pd

In [32]:
df=pd.read_csv('project3.csv',header=None)
df.columns=['one','two','three']

In [30]:
def get_valid(s):
    values=[s.one,s.two,s.three]
    max_val = max(values)
    sum_val = sum(values)-max_val
    return sum_val>max_val

In [31]:
df['valid']=df.apply(get_valid,axis=1)
len(df[df.valid==True])

993

In [33]:
def get_valid(s):
    max_val = s.max()
    sum_val = s.sum()-max_val
    return sum_val>max_val

In [36]:
df=pd.read_csv('project3.csv',header=None)
df['valid2']=df.apply(lambda x: x.sum()-x.max() > x.max(),axis=1)
len(df[df.valid2==True])

993

In [56]:
df=pd.read_csv('project3.csv',header=None)
df = pd.concat([df[0],df[1],df[2]])
df = pd.DataFrame([df[df.index%3==i].reset_index(drop=True) for i in range(3)],index=None).transpose()
df['valid2']=df.apply(lambda x: x.sum()-x.max() > x.max(),axis=1)
len(df[df.valid2==True])

1849

In [54]:
df

        0    1    2
0     541  827  660
1      39  229  237
2     898  101  813
3     603  335  382
4     545  657  823
5     370  101  295
6     656  634  819
7     504  760  733
8     197  357  544
9     604   90  609
10    313  421  278
11    299  362  353
12    992  850  251
13    810  959  450
14    849  419  995
15    711   17  722
16    920  905  794
17    317  145  445
18    935  784  255
19    521  490  163
20    771  914  271
21    411  370   61
22    333  269  477
23    610  650  145
24    758  524  760
25    360  456  510
26    886  356  685
27    253  868  811
28    205  707  835
29    496  484   33
...   ...  ...  ...
1881  308  894  908
1882  430  435   10
1883  205  873  699
1884  978  974  223
1885  965   62  987
1886  512  110  422
1887  992  962  120
1888  259  688  715
1889  309  129  267
1890  744  834  275
1891   92  205  122
1892  734  760   24
1893  333  277  369
1894  469  437   68
1895  792  660  946
1896  605  758  269
1897  351  768  751
1898  474  949  771
1899  561  709  668
1900  913  122  808
1901  614  679  227
1902  523  543   31
1903  863  337  885
1904  781  785   36
1905  367  927  936
1906  289   91  256
1907  489  540  321
1908  371  653  810
1909  281  408  454
1910  293  103  254

[1911 rows x 3 columns]

      index    0
0         0  541
1         1  827
2         2  660
3         3   39
4         4  229
5         5  237
6         6  898
7         7  101
8         8  813
9         9  603
10       10  335
11       11  382
12       12  545
13       13  657
14       14  823
15       15  370
16       16  101
17       17  295
18       18  656
19       19  634
20       20  819
21       21  504
22       22  760
23       23  733
24       24  197
25       25  357
26       26  544
27       27  604
28       28   90
29       29  609
...     ...  ...
5703   1881  614
5704   1882  679
5705   1883  227
5706   1884  523
5707   1885  543
5708   1886   31
5709   1887  863
5710   1888  337
5711   1889  885
5712   1890  781
5713   1891  785
5714   1892   36
5715   1893  367
5716   1894  927
5717   1895  936
5718   1896  289
5719   1897   91
5720   1898  256
5721   1899  489
5722   1900  540
5723   1901  321
5724   1902  371
5725   1903  653
5726   1904  810
5727   1905  281
5728   1906  408
5729   1907  454
5730   1908  293
5731   1909  103
5732   1910  254

[5733 rows x 2 columns]